import { useState } from 'react';
import { Card, Alert, Input, Button, Typography, Spin } from 'antd';
import { diagnose } from '../api/diagnosisApi';

const { Title, Paragraph } = Typography;

function AIDiagnosisPage() {
  const [taskId, setTaskId] = useState('');
  const [loading, setLoading] = useState(false);
  const [diagnosis, setDiagnosis] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleDiagnose = async () => {
    if (!taskId.trim()) return;
    setLoading(true);
    setError(null);
    setDiagnosis(null);

    try {
      const result = await diagnose(taskId.trim());
      setDiagnosis(result.diagnosis);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'An unexpected error occurred');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      <Title level={2}>AI Diagnosis</Title>

      <Card style={{ marginBottom: 24 }}>
        <Input
          size="large"
          placeholder="Enter task ID (e.g., a1b2c3d4)"
          value={taskId}
          onChange={(e) => setTaskId(e.target.value)}
          onPressEnter={handleDiagnose}
          style={{ marginBottom: 16 }}
        />
        <Button
          type="primary"
          onClick={handleDiagnose}
          loading={loading}
          disabled={!taskId.trim()}
        >
          Diagnose
        </Button>
      </Card>

      {loading && (
        <div style={{ textAlign: 'center', margin: 24 }}>
          <Spin size="large" tip="Running AI diagnosis..." />
        </div>
      )}

      {error && (
        <Alert
          message="Diagnosis Failed"
          description={error}
          type="error"
          showIcon
          closable
          style={{ marginBottom: 24 }}
        />
      )}

      {diagnosis && (
        <Card title="Diagnosis Result">
          <Alert
            message="Preliminary AI Diagnosis"
            description="This diagnosis was generated by an AI model and is NOT the confirmed root cause. A human engineer must review and validate before treating as fact."
            type="warning"
            showIcon
            style={{ marginBottom: 16 }}
          />
          <Paragraph>
            <pre style={{ whiteSpace: 'pre-wrap', wordBreak: 'break-word', fontFamily: 'inherit' }}>
              {diagnosis}
            </pre>
          </Paragraph>
        </Card>
      )}
    </div>
  );
}

export default AIDiagnosisPage;
